### PR TITLE
fix cached static crash

### PR DESCRIPTION
**Pull request by aamalev**
vary big patch

### CODE REVIEW

**Comment by asvetlov** [comment]
Well, it's possible when app return non-HTTP exception with redirection status code

**Comment by jettify** [comment]
Is it frequent case? May be we should raise exception instead of trying to render?

**Comment by asvetlov** [comment]
No, if user want to return basic response (even `StreamResponse`, most likely `Response`) with redirection status code and properly filed `Location` header -- this is totally correct answer and should be processed without exception from `aiohttp_debugtoolbar`  middleware.

But I'd like to have a test for the case.

@aamalev would you add it? Should be very trivial task.

**Comment by jettify** [comment]
fixed in https://github.com/aio-libs/aiohttp-debugtoolbar/pull/174

**Pull request closed without merging**
